-- CHESS MOD
-- =================================================
-- chess/rules.lua
-- =================================================
-- Registers the chess pieces
--
-- Contents:
--
-- [func] update(command) - Manages /move rook to A6
-- [func] checkMove(piece,target) - checks the piece can get there
-- [func] takePiece(piece)
-- =================================================